parameters:
    lightsaml_sp.route.discovery: lightsaml_sp.discovery
    lightsaml.route.login_check: lightsaml_sp.login_check

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $discoveryRoute: '%lightsaml_sp.route.discovery%'

    LightSaml\SpBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,LightSamlSpBundle.php}'

    LightSaml\SpBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    lightsaml_sp.username_mapper.simple:
        class: LightSaml\SpBundle\Security\User\SimpleUsernameMapper
        arguments:
            - []

    lightsaml_sp.attribute_mapper.simple:
        class: LightSaml\SpBundle\Security\User\SimpleAttributeMapper

    lightsaml_sp.token_factory:
        class: LightSaml\SpBundle\Security\Authentication\Token\SamlSpTokenFactory

    LightSaml\SymfonyBridgeBundle\Bridge\Container\BuildContainer: '@lightsaml.container.build'
    LightSaml\Builder\Profile\Metadata\MetadataProfileBuilder: '@ligthsaml.profile.metadata'
    LightSaml\Builder\Profile\WebBrowserSso\Sp\SsoSpSendAuthnRequestProfileBuilderFactory: '@ligthsaml.profile.login_factory'
